  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;             ██████  ██████ ██████  ███████             ;;  
  ;;            ██      ██      ██   ██ ██                  ;;  
  ;;            ██      ██      ██████  ███████             ;;  
  ;;            ██      ██      ██   ██      ██             ;;  
  ;;             ██████  ██████ ██   ██ ███████             ;;  
  ;;                                                        ;;  
  ;;              https://github.com/336conaN               ;;  
  ;;             https://codeberg.org/336conaN              ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;               Please check the README!                 ;;  
  ;;  https://github.com/336conaN/ccrs/blob/main/README.md  ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

[Variables]
Scale=1.0
Theme=Default
BorderWidth=1
TextFont=SF Pro
NerdFont=RobotoMono Nerd Font Propo
FontWeightMain=600
FontWeightSub=400
CornerRadiusOutside=8
CornerRadiusInside=6
DisableContextMenu=false
OpenConfigOnClick=true
; WinFetchLogo=%USERPROFILE%\Pictures\Other\windows.png
; WslFetchLogo=%USERPROFILE%\Pictures\Other\linux.png
ShareXPath=C:\Program Files\ShareX\ShareX.exe
ScreenshotsFolder=%USERPROFILE%\Pictures
VisualizerFrequencyResolution=1024
VisualizerSensitivity=35.0
CpuTempIndex=2
CpuUsageIndex=1
GpuTempIndex=6
GpuUsageIndex=7
DiskTempIndex=4
DiskUsageIndex=5
MemoryTempIndex=3
MemoryUsageIndex=0
; Gif1FullPath="%USERPROFILE%\Pictures\wave.png"
; Gif1FramesCount=222
; Gif1RefreshRate=60
; Shortcut1Icon="%USERPROFILE%\Pictures\explorer.png"
; Shortcut1Color=#Accent1#
; Shortcut1Command="explorer.exe"

