  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;             ██████  ██████ ██████  ███████             ;;  
  ;;            ██      ██      ██   ██ ██                  ;;  
  ;;            ██      ██      ██████  ███████             ;;  
  ;;            ██      ██      ██   ██      ██             ;;  
  ;;             ██████  ██████ ██   ██ ███████             ;;  
  ;;                                                        ;;  
  ;;             https://github.com/336conaN                ;;  
  ;;             https://codeberg.org/336conaN              ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;               Please check the README!                 ;;  
  ;;  https://github.com/336conaN/ccrs/blob/main/README.md  ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

[Variables]
Theme=Default
; ProfilePicturePath=%USERPROFILE%\Pictures\profile.png
Font=RobotoMono Nerd Font Propo
FontWeight=600
Scale=1.0
BorderWidth=1
CornerRadiusOutside=8
CornerRadiusInside=6
DisableContextMenu=false
OpenConfigOnClick=true
ShareXPath=C:\Program Files\ShareX\ShareX.exe
; ScreenshotsFolder=%USERPROFILE%\Pictures\Screenshots
VisualizerFrequencyResolution=1024
VisualizerSensitivity=35.0
CpuTempIndex=2
CpuUsageIndex=1
GpuTempIndex=6
GpuUsageIndex=7
DiskTempIndex=4
DiskUsageIndex=5
MemoryTempIndex=3
MemoryUsageIndex=0
; Gif1FullPath="%USERPROFILE%\Pictures\wave.png"
; Gif1FramesCount=222
; Gif1RefreshRate=60
; Image1="%USERPROFILE%\Pictures\image.png"
; Shortcut1Icon="%USERPROFILE%\Pictures\explorer.png"
; Shortcut1Command="explorer.exe"
; List1Icon=
; List1Entry1Label=Desktop
; List1Entry1Command=%USERPROFILE%\Desktop
; List1Entry2Label=Downloads
; List1Entry2Command=%USERPROFILE%\Downloads
; List1Entry3Label=Documents
; List1Entry3Command=%USERPROFILE%\Documents
; List1Entry4Label=Home
; List1Entry4Command=%USERPROFILE%
