  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;             ██████  ██████ ██████  ███████             ;;  
  ;;            ██      ██      ██   ██ ██                  ;;  
  ;;            ██      ██      ██████  ███████             ;;  
  ;;            ██      ██      ██   ██      ██             ;;  
  ;;             ██████  ██████ ██   ██ ███████             ;;  
  ;;                                                        ;;  
  ;;             https://github.com/336conaN                ;;  
  ;;             https://codeberg.org/336conaN              ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;               Please check the README!                 ;;  
  ;;  https://github.com/336conaN/ccrs/blob/main/README.md  ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

[Variables]
Scale=1
Theme=catppuccin-mocha
Font=SFMono Nerd Font Mono
ProfilePicture=#@#Assets\profile.png
UserName=conaN
ShareX=C:\Program Files\ShareX\ShareX.exe
Screenshots=C:\Users\conaN\Pictures\Screenshots
CornerRadiusOutside=8
CornerRadiusInside=6
BorderWidthOutside=0
BorderWidthInside=0
GifName=wave
GifFrames=80
CpuTempIndex=2
CpuUsageIndex=1
GpuTempIndex=6
GpuUsageIndex=7
DriveTempIndex=4
DriveUsageIndex=5
RamTempIndex=3
RamUsageIndex=0
GitRepo1Name=ccrs
GitRepo1PathWSL=~/git/ccrs
GitRepo1PathWindows=\\wsl.localhost\NixOS\home\nixos\git\ccrs
GitRepo2Name=website
GitRepo2PathWSL=~/git/website
GitRepo2PathWindows=\\wsl.localhost\NixOS\home\nixos\git\website
GitRepo3Name=.win
GitRepo3PathWSL=~/dotfiles/.win
GitRepo3PathWindows=\\wsl.localhost\NixOS\home\nixos\dotfiles\.win
GitRepo4Name=.wsl
GitRepo4PathWSL=~/dotfiles/.wsl
GitRepo4PathWindows=\\wsl.localhost\NixOS\home\nixos\dotfiles\.wsl

