  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;             ██████  ██████ ██████  ███████             ;;  
  ;;            ██      ██      ██   ██ ██                  ;;  
  ;;            ██      ██      ██████  ███████             ;;  
  ;;            ██      ██      ██   ██      ██             ;;  
  ;;             ██████  ██████ ██   ██ ███████             ;;  
  ;;                                                        ;;  
  ;;             https://github.com/336conaN                ;;  
  ;;             https://codeberg.org/336conaN              ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;               Please check the README!                 ;;  
  ;;  https://github.com/336conaN/ccrs/blob/main/README.md  ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

[Variables]
Scale=1
Theme=catppuccin-mocha
Font=SFMono Nerd Font Mono
ProfilePicture=#@#Assets\profile.png
Name=conaN
UserName=@336conaN
Gallery=C:\Users\conaN\Pictures\Screenshots
CornerRadiusOutside=8
CornerRadiusInside=6
BorderWidthOutside=0
BorderWidthInside=0
GifName=wave
GifFrames=80
CpuTempIndex=2
CpuUsageIndex=1
GpuTempIndex=6
GpuUsageIndex=7
DriveTempIndex=4
DriveUsageIndex=5
RamTempIndex=3
RamUsageIndex=0
GitRepo1Name=ccrs
GitRepo1Path=~/git/ccrs
GitRepo2Name=website
GitRepo2Path=~/git/website
GitRepo3Name=.win
GitRepo3Path=~/dotfiles/.win
GitRepo4Name=.wsl
GitRepo4Path=~/dotfiles/.wsl

