  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;             ██████  ██████ ██████  ███████             ;;  
  ;;            ██      ██      ██   ██ ██                  ;;  
  ;;            ██      ██      ██████  ███████             ;;  
  ;;            ██      ██      ██   ██      ██             ;;  
  ;;             ██████  ██████ ██   ██ ███████             ;;  
  ;;                                                        ;;  
  ;;             https://github.com/336conaN                ;;  
  ;;             https://codeberg.org/336conaN              ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  
  ;;                                                        ;;  
  ;;               Please check the README!                 ;;  
  ;;  https://github.com/336conaN/ccrs/blob/main/README.md  ;;  
  ;;                                                        ;;  
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;  

[Variables]
Scale=1
Theme=catppuccin-mocha
ProfilePicture=#@#Assets\profile.png
Gallery=C:\Users\conaN\Pictures\Screenshots
MonoFont=SFMono Nerd Font Mono
TextFont=SF Pro
CornerRadiusOutside=8
CornerRadiusInside=6
BorderWidthOutside=0
BorderWidthInside=0
GitHub=336conaN
CodeBerg=336conaN

