[mAudio]
Measure=Plugin
Plugin=AudioLevel
Port=Output
FFTSize=#VisualizerFrequencyResolution#
Sensitivity=#VisualizerSensitivity#
Bands=24

[mBand0]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=0

[mBand1]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=1

[mBand2]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=2

[mBand3]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=3

[mBand4]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=4

[mBand5]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=5

[mBand6]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=6

[mBand7]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=7

[mBand8]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=8

[mBand9]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=9

[mBand10]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=10

[mBand11]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=11
[mBand12]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=12

[mBand13]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=13

[mBand14]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=14

[mBand15]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=15

[mBand16]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=16

[mBand17]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=17

[mBand18]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=18

[mBand19]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=19

[mBand20]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=20

[mBand21]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=21

[mBand22]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=22

[mBand23]
Measure=Plugin
Plugin=AudioLevel
Parent=mAudio
Type=Band
BandIdx=23
