[Variables]

Size="*#Scale#"
Position="*#Scale#+(#BorderWidth#/2)"

1x1=Rectangle (0#Position#),(0#Position#),(35#Size#),(35#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
2x2=Rectangle (0#Position#),(0#Position#),(80#Size#),(80#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x4=Rectangle (0#Position#),(0#Position#),(170#Size#),(170#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
6x6=Rectangle (0#Position#),(0#Position#),(260#Size#),(260#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x8=Rectangle (0#Position#),(0#Position#),(350#Size#),(350#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x1=Rectangle (0#Position#),(0#Position#),(350#Size#),(35#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
1x8=Rectangle (0#Position#),(0#Position#),(35#Size#),(350#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x1=Rectangle (0#Position#),(0#Position#),(170#Size#),(35#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
1x4=Rectangle (0#Position#),(0#Position#),(35#Size#),(170#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x4=Rectangle (0#Position#),(0#Position#),(350#Size#),(170#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x8=Rectangle (0#Position#),(0#Position#),(170#Size#),(350#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x2=Rectangle (0#Position#),(0#Position#),(350#Size#),(80#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x2=Rectangle (0#Position#),(0#Position#),(80#Size#),(350#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x5=Rectangle (0#Position#),(0#Position#),(170#Size#),(215#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
5x4=Rectangle (0#Position#),(0#Position#),(215#Size#),(170#Size#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
