[Variables]
1x1=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(35*#Scale#),(35*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
2x2=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(80*#Scale#),(80*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
4x4=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(170*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
6x6=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(260*#Scale#),(260*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
8x8=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(350*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
8x1=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(350*#Scale#),(35*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
1x8=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(35*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
4x1=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(170*#Scale#),(35*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
1x4=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(35*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
8x4=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(350*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
4x8=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(170*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
8x2=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(350*#Scale#),(80*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
8x2=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(80*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
4x5=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(170*#Scale#),(215*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
5x4=Rectangle (#BorderWidth#/2),(#BorderWidth#/2),(215*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #Border#
