[Variables]
1x1=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(35*#Scale#),(35*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
2x2=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(80*#Scale#),(80*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x4=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(170*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
6x6=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(260*#Scale#),(260*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x8=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(350*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x1=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(350*#Scale#),(35*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
1x8=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(35*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x1=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(170*#Scale#),(35*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
1x4=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(35*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x4=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(350*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x8=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(170*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x2=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(350*#Scale#),(80*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
8x2=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(80*#Scale#),(350*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
4x5=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(170*#Scale#),(215*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
5x4=Rectangle ((0*#Scale#)+(0.5*#BorderWidth#)),((0*#Scale#)+(0.5*#BorderWidth#)),(215*#Scale#),(170*#Scale#),#CornerRadiusOutside# | Fillcolor #Background# | Strokewidth #BorderWidth# | Strokecolor #BorderColor#
